bg_image.putalpha(int(255 * alpha))
# bg_image = bg_image.resize((1290, 720), Image.LANCZOS)
# background_image = ImageTk.PhotoImage(bg_image)
# background_label = tk.Label(window, image=background_image)
# background_label.place(x=0, y=0, relwidth=1, relheight=1)
